### ISSUE TITLE
Unable to upgrade to 1.3.5

### ISSUE THREAD

**Issue by pjhenning** [flox/flox#2457]
**Describe the bug:**
When changing the version of Flox in my system flake.nix and rebuilding, I get the following error:
```
error: builder for '/nix/store/zckk4kn4cp8m3gvdnsma7ibxmwmzwbnl-flox-pkgdb-1.3.5.drv' failed with exit code 2;
> src/realisepkgs/realise.cc:60:9: error: no member named 'force' in 'nix::eval_cache::CachedEvalError'
>       e.force();
>       ~ ^
```
I am using nix-darwin on MacOS 12.7.6

**Steps to reproduce:**
1. `nix.conf`: https://gist.github.com/pjhenning/5f1d5211e8239358ed07494644532eca
2. `flake.nix`: https://gist.github.com/pjhenning/658d23f82902f4eb47fdc51b559bc680
3. run `darwin-rebuild switch --flake /Users/LOGINUSER/.config` (`flake.nix` linked above is located at `/Users/LOGINUSER/.config/flake.nix`)

Result:
System derivation fails to build.

Expected:
System derivation builds with Flox 1.3.5.

**`uname -a` output:**
Darwin MBP.lan 21.6.0 Darwin Kernel Version 21.6.0: Mon Jun 24 00:56:10 PDT 2024; root:xnu-8020.240.18.709.2~1/RELEASE_X86_64 x86_64

**Comment by mkenigs** [comment]
Do you have a follows or something for nixpkgs? I'd expect that error if you're somehow injecting a different version of Nix into the build of Flox than what we have pinned

**Comment by pjhenning** [comment]
Thats a much quicker response than I was expecting! The following in `inputs` may be relevant to your question:
```
nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-24.11-darwin";
darwin.url = "github:lnl7/nix-darwin";
darwin.inputs.nixpkgs.follows = "nixpkgs";
home-manager.url = "github:nix-community/home-manager/release-24.11";
home-manager.inputs.nixpkgs.follows = "nixpkgs";
```

**Comment by pjhenning** [comment]
Should probably include this as well, not sure that its the exact compile command that failed but it serves to document the includes:
```
clang++  -Wall -Wextra -Wpedantic -Wno-gnu-zero-variadic-macro-arguments '-I/private/tmp/nix-build-flox-pkgdb-1.3.5.drv-0/pkgdb/include' '-DFLOX_PKGDB_VERSION=""' -isystem /nix/store/2knmh88ijbvp3d9y80sqmv6nl9r5ra8h-sqlite-3.45.3-dev/include -isystem /nix/store/jcnx2jdi8l40d54ycyfpyjhwdk6idynl-sqlite3pp-1.0.8/include -isystem /nix/store/qs57h61scmns7xvxxfh0xwg7nnr5q1n2-argparse-3.0/include -isystem /nix/store/qrwwwkbsinfwpl7l6733lw6m3x69mq17-boost-1.81.0-dev/include -std=c++2a -isystem /nix/store/siylkc20xrnj62317pwxddihzaahy7dd-nix-2.18.5-dev/include -isystem /nix/store/mcj2kqzjqsx2w34mbaqx99glj0jc8lsx-boehm-gc-8.2.6-dev/include -include /nix/store/siylkc20xrnj62317pwxddihzaahy7dd-nix-2.18.5-dev/include/nix/config.h -isystem /nix/store/ypx96fjpbnqm7z6al5dhgglhssak48n6-nlohmann_json-3.11.3/include -isystem /nix/store/vi9ssavcz29q6ibplicnzjhxk8pzb075-toml11-3.7.1/include -isystem /nix/store/p79jbn45drmxk3pvj26cz23w7rvpg9qw-yaml-cpp-0.8.0/include -isystem /nix/store/wwhrvg6mirj8j1iqnvig8bmc945njhyj-cpp-semver-unstabble-2021-12-10/include '-DNIXPKGS_CACERT_BUNDLE_CRT="/nix/store/i5fn2w5gm5wxk5vhphiq4yxbv7hvgm01-nss-cacert-3.101/etc/ssl/certs/ca-bundle.crt"'   -c -o src/util.o src/util.cc
```

**Comment by mkenigs** [comment]
> Thats a much quicker response than I was expecting! The following in `inputs` may be relevant to your question:
> 
> ```
> nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-24.11-darwin";
> ```

Oh sorry I missed you'd linked your entire flake.nix above. I'll take another look tomorrow

**Comment by mkenigs** [comment]
`flake.nix` looks okay, wondering if the flox entry in your `flake.lock` is stale. Can you do a `nix flake lock --update-input flox`?

**Comment by ysndr** [comment]
I believe i've seen this issue as well before. then it was the nix version being linked against.

`CachedEvalError::force` is present in nix [2.18.**8**](https://github.com/NixOS/nix/blob/501a805fcd4a90e2bc112e9547417cfc4e04ca66/src/libexpr/eval-cache.hh#L29) but not in [2.18.**5**](https://github.com/NixOS/nix/blob/217fadd993da88294d0393af374b638afd99b169/src/libexpr/eval-cache.hh#L29) which this is trying to use judging from your `clang++ ...` snippet.

FWIW that was apparently added in 2.18.6 originally: https://github.com/NixOS/nix/commit/8e5ec819f8027ecedc5173f49c705195efda2a1c

**Comment by pjhenning** [comment]
> `flake.nix` looks okay, wondering if the flox entry in your `flake.lock` is stale. Can you do a `nix flake lock --update-input flox`?

This did not make any difference for me unfortunately.

**Comment by pjhenning** [comment]
> I believe i've seen this issue as well before. then it was the nix version being linked against.
> 
> `CachedEvalError::force` is present in nix [2.18.**8**](https://github.com/NixOS/nix/blob/501a805fcd4a90e2bc112e9547417cfc4e04ca66/src/libexpr/eval-cache.hh#L29) but not in [2.18.**5**](https://github.com/NixOS/nix/blob/217fadd993da88294d0393af374b638afd99b169/src/libexpr/eval-cache.hh#L29) which this is trying to use judging from your `clang++ ...` snippet.
> 
> FWIW that was apparently added in 2.18.6 originally: [NixOS/nix@8e5ec81](https://github.com/NixOS/nix/commit/8e5ec819f8027ecedc5173f49c705195efda2a1c)

I changed `configuration.nix.package` in `flake.nix` from `pkgs.nixVersions.stable` to `pkgs.nixVersions.latest`, but the build is still trying to link against `/nix/store/siylkc20xrnj62317pwxddihzaahy7dd-nix-2.18.5-dev/include`.

**Comment by pjhenning** [comment]
Running `nix --version` currently gives "nix (Nix) 2.24.10"

**Comment by mkenigs** [comment]
If you do a `nix build github:flox/flox/v1.3.5#packages.x86_64-darwin.default`, does that work? If so, I'm a little stumped because from what I see in your `flake.nix` that seems to be exactly what you're using, unless there's something stale in your `flake.lock`. `nix --version` shouldn't matter because that's not the Nix that Flox is being compiled against. We're compiling against a Nix provided by a flake input.

**Comment by ysndr** [comment]
Just by chance, did you only update your flake.nix or also relocked it?
You could try running `nix flake lock --update-input flox`.
Possibly nix didn't deeply update your lockfile (would surprise me and I'd consider that a bug in my book but I also don't consider it impossible)

**Comment by mkenigs** [comment]
> > `flake.nix` looks okay, wondering if the flox entry in your `flake.lock` is stale. Can you do a `nix flake lock --update-input flox`?
> 
> This did not make any difference for me unfortunately.

He already tried that command specifically. Might be worth completely removing flake.lock

**Comment by pjhenning** [comment]
I deleted `flake.lock`, ran `nix flake update --flake /Users/LOGINUSER/.config`, then ran `darwin-rebuild switch --flake /Users/LOGINUSER/.config`. Build was successful, now `flox --version` gives "1.3.5-g0b62cdc". Pretty sure it was the `nix flake update` that did the trick and not deleting the lock file. On the one hand I feel a bit silly that I forgot to run the update command, but on the other hand the only step explicitly given in the Flox docs for upgrading is to change the Flox version in the flake. Not sure whether this is something that y'all consider to be within the scope of your responsibility for documenting. I certainly don't blame you for not covering it currently in the docs, nor do I blame you for the rough edges of using Nix with flakes.

**Comment by mkenigs** [comment]
I think we should add a `nix flake update` to the docs https://github.com/flox/floxdocs/blob/ad4a6744f84fb2fb3a232fa3418bce9ab6bbfd6a/docs/install-flox.md?plain=1#L668

**Comment by mkenigs** [comment]
Added a note to the docs in https://github.com/flox/floxdocs/pull/125
